export const GET_LOGGED_IN = 'USER_LOG_IN';
export const GET_LOGGED_OUT = 'USER_LOG_OUT';
export const SHOW_ALL_FEEDS = 'SHOW_ALL_FEEDS';
export const SHOW_UP_LOGIN_FORM = 'SHOW_UP_LOGIN_FORM';
export const SHOW_UP_RECEIPT_SUBMISSION_FORM = 'SHOW_UP_RECEIPT_SUBMISSION_FORM';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SHOW_UP_AUTH_REQUEST_COMPLETION_NOTICE = 'SHOW_UP_AUTH_REQUEST_COMPLETION_NOTICE';
