export const USER_LOG_IN = 'USER_LOG_IN';
export const USER_LOG_OUT = 'USER_LOG_OUT';
export const FEED_LIST = 'FEED_LIST';
export const ON_SEARCH = 'ON_SEARCH';
export const SUBMISSION_ACADEMY_INFOS = 'SUBMISSION_ACADEMY_INFOS';
export const ACADEMY_DETAILS = 'ACADEMY_DETAILS';
export const TOGGLING_REVIEWS = 'TOGGLING_REVIEWS';
export const TOGGLING_REVIEW_INPUT = 'TOGGLING_REVIEW_INPUT';
