export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SHOW_UP_LOGIN_FORM = 'SHOW_UP_LOGIN_FORM';
export const SHOW_UP_RECEIPT_SUBMISSION_FORM = 'SHOW_UP_RECEIPT_SUBMISSION_FORM';
export const SHOW_UP_AUTH_REQUEST_COMPLETION_NOTICE = 'SHOW_UP_AUTH_REQUEST_COMPLETION_NOTICE';
export const ALREADY_REGISTERED_USER_NOTICE = 'ALREADY_REGISTERED_USER_NOTICE';
export const REGISTER_REQUIRED_NOTICE = 'REGISTER_REQUIRED_NOTICE';
